export const AI_TASKS = {
  RESUME_ANALYSIS: 'AI_RESUME_ANALYSIS',
  JOB_ANALYSIS: 'AI_JOB_ANALYSIS',
  SEMANTIC_MATCH: 'AI_SEMANTIC_MATCH',
  INTERVIEW_QUESTIONS: 'AI_INTERVIEW_QUESTIONS',
  SKILL_GAP: 'AI_SKILL_GAP',
  CAREER_RECOMMENDATION: 'AI_CAREER_RECOMMENDATION',
  DIAGNOSTIC_TEST: 'AI_DIAGNOSTIC_TEST'
};
