export const RecommendationTypes = {
  JOB: 'JOB_RECOMMENDATION',
  CANDIDATE: 'CANDIDATE_RECOMMENDATION',
  LEARNING: 'LEARNING_RECOMMENDATION',
  CAREER: 'CAREER_RECOMMENDATION',
  SKILL: 'SKILL_RECOMMENDATION'
};
