export const NOTIFICATION_TYPES = {
  // Candidate
  APPLICATION_SUBMITTED: 'APPLICATION_SUBMITTED',
  APPLICATION_REVIEWED: 'APPLICATION_REVIEWED',
  APPLICATION_ACCEPTED: 'APPLICATION_ACCEPTED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  INTERVIEW_SCHEDULED: 'INTERVIEW_SCHEDULED',
  INTERVIEW_REMINDER: 'INTERVIEW_REMINDER',
  OFFER_SENT: 'OFFER_SENT',
  PROFILE_VERIFIED: 'PROFILE_VERIFIED',
  
  // Company
  NEW_APPLICANT: 'NEW_APPLICANT',
  CANDIDATE_ACCEPTED: 'CANDIDATE_ACCEPTED',
  CANDIDATE_REJECTED: 'CANDIDATE_REJECTED',
  COMPANY_APPROVED: 'COMPANY_APPROVED',
  SUBSCRIPTION_EXPIRING: 'SUBSCRIPTION_EXPIRING',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',

  // Admin
  NEW_COMPANY_REGISTRATION: 'NEW_COMPANY_REGISTRATION',
  VERIFICATION_PENDING: 'VERIFICATION_PENDING',

  // Communication
  MESSAGE_SENT: 'MESSAGE_SENT'
};
